---
name: ConsoleExporter
main: kim\present\consoleexporter\Main
version: 1.1.2
api: [ 5.0.0 ]
author: PresentKim
description: Recording console and exports to html!

commands:
  consoleexport:
    description: Start console recording or Stop and exports to HTML
    aliases: [ ce ]
    permission: consoleexporter.cmd

permissions:
  consoleexporter.cmd:
    description: Allows use consoleexport command
    default: op
...
