---
name: refConsoleExporter
main: ref\product\consoleexporter\Main
version: 1.0.0
api: [ 4.0.0 ]
authors: [ ref-team, PresentKim ]
description: Recording console and exports to html!

commands:
  consoleexport:
    description: Start console recording or Stop and exports to HTML
    aliases: [ ce ]
    permission: consoleexporter.cmd

permissions:
  consoleexporter.cmd:
    description: Allows use consoleexport command
    default: op
...